version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql_wptest
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wptest
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wptest-network

  wordpress:
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress_test
    restart: unless-stopped
    depends_on: 
      - db
    env_file: .env
    environment: 
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wptest
    volumes:
      - wordpress:/var/www/html
    networks:
      - wptest-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: nginx_wptest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - wptest-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file: .env
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - PMA_ARBITRARY=1
    networks:
      - wptest-network

volumes:
  dbdata:
  wordpress:
  
networks:
  wptest-network:
    driver: bridge

